CREATE TABLE CAD_COR (
	ID_COR INT, 
	DESCRICAO VARCHAR(100),
	PRIMARY KEY (ID_COR));

CREATE TABLE CAD_VEICULO (
	PLACA VARCHAR(8), 
	ANO_MODELO INT,
	ATUALIZADO_EM DATE,
	ID_COR INT,
	ANO_FABRICACAO INT,
	ATIVO BOOLEAN,
	PRIMARY KEY (PLACA),
	FOREIGN KEY (ID_COR) REFERENCES CAD_COR(ID_COR));
	
